// flow-typed signature: 2be3aca553ad6f4e86ac81ce10137e67
// flow-typed version: <<STUB>>/@storybook/knobs_v3.1.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/knobs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/knobs' {
  declare module.exports: any;
}
